# Generated by Django 5.0.6 on 2024-06-15 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_debt_delete_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
