# Generated by Django 5.0.6 on 2024-06-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='debt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='core.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
