# Generated by Django 5.0.6 on 2024-06-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_debt_interest_rate_alter_debt_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
