# Generated by Django 5.0.6 on 2024-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_debt_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='is_bad_debt',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT PAID', 'Not Paid'), ('BAD DEBT', 'Bad Debt')], default='Not Paid', max_length=255),
        ),
    ]
