# Generated by Django 5.0.6 on 2024-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_debt_is_bad_debt_remove_debt_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT PAID', 'Not Paid'), ('BAD DEBT', 'Bad Debt')], default='NOT PAID', max_length=255),
        ),
    ]
