# Generated by Django 5.0.6 on 2024-06-17 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_debt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI-MONTHLY', 'Bi-Monthly'), ('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-Weekly'), ('QUARTERLY', 'Quarterly'), ('SEMI-ANNUALLY', 'Semi-Annually'), ('ANNUALLY', 'Annually')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
